### ISSUE TITLE
Questions about init ETL from spec

### ISSUE THREAD

**Issue by yingca1** [NVIDIA/aistore#141]
1. Why is the `["sh", "-c", "/server"]` command mandatory when using `ais etl init spec`?
    - https://github.com/NVIDIA/aistore/blob/1ec3825e93ad2b424c03027e95505d79f507cbd5/ext/etl/boot.go#L228C34-L228C34
3. Where can I find the source code for the `server`?

**Comment by gaikwadabhishek** [comment]
Hello @yingca1 !
1. The command param is [only replaced](https://github.com/NVIDIA/aistore/blob/1ec3825e93ad2b424c03027e95505d79f507cbd5/ext/etl/boot.go#L223) when the communication type is `io`. More information on [communication types](https://github.com/NVIDIA/aistore/blob/master/docs/etl.md#communication-mechanisms). Otherwise, we want you to provide command to run your own transformer server (if there exists one) in the pods spec.yaml file. Here are some sample transformers - https://github.com/NVIDIA/ais-etl/tree/master/transformers.

2. The server executable file for running io-comm is made here https://github.com/NVIDIA/ais-etl/blob/master/runtime/python/io-comm/Makefile#L3. We are working on updating the `ais-etl` repo.
