### ISSUE TITLE
Locality/Availability Zone awareness?

### ISSUE THREAD

**Issue by Samrose-Ahmed** [NVIDIA/aistore#185]
Is aistore aware of rack/availability zone? This is relevant for serving read to clients and also for rebalancing data to ensure no inter-AZ costs.

**Comment by gaikwadabhishek** [comment]
Hey @Samrose-Ahmed,

> aistore aware of rack/availability zone? 

AIStore is not designed with rack or availability zone awareness in mind. The recommended approach is to deploy separate AIStore clusters in each region. For example, if your GPUs are located on both the East Coast and West Coast, setting up two distinct AIStore clusters is highly recommended. Each cluster will serve the GPUs within its respective region, with reduced latency, and stable throughputs. Additionally, since your persistent data source is S3 (assuming), there will be no cross-region communication. The two clusters in the example will read and write to s3 independently and changes will be reflected in the other cluster in subsequent GET operations. This is how we currently do it at NVIDIA.
