### ISSUE TITLE
K8s Deployment Issue - Signing keys of AuthN and AIStore dont match

### ISSUE THREAD

**Issue by liuzhiyuan562** [NVIDIA/aistore#187]
I use the command 
(kubespray-venv) zy@zy-ThinkPad-X1-Carbon-Gen-11:~/kubernetes/kubespray/ais-k8s$ ansible-playbook -i playbooks/hosts.ini playbooks/ais-deployment/ais_deploy_cluster.yml -K -e cluster=ais
and I met a question and I can't find a solution.
![Image](https://github.com/user-attachments/assets/e48f7399-33bc-42f9-ab46-29f35d553eb6)

the /tmp/ais.yaml is below.(I change the name to /tmp/ais.log, because .yaml isn't allowed)
[ais.log](https://github.com/user-attachments/files/16990813/ais.log)

**Comment by aaronnw** [comment]
Please check that you are using the latest operator and aisnode versions. `stateStorageClass` was added in operator v1.2.0 https://github.com/NVIDIA/ais-k8s/releases/tag/v1.2.0 -- it looks like your current operator does not have the latest AIS custom resource definition.

**Comment by aaronnw** [comment]
Alternatively, hostPathPrefix is still supported for AIS node state storage  (though deprecated). If you provide this option, you can specify a hostPath for local state to be stored on rather than a dynamically configured local volume. (note stateStorageClass will take precedence if both are provided)

**Comment by liuzhiyuan562** [comment]
Thanks! And I met another question when I set up a debugging pod
![Image](https://github.com/user-attachments/assets/150562b1-fdcb-476f-9d72-fe308029159a)
![Image](https://github.com/user-attachments/assets/dfdbe139-fb4c-4c24-9ae1-9292164215cf)

**Comment by liuzhiyuan562** [comment]
And I change the command in aisnode_debug.yaml
![Image](https://github.com/user-attachments/assets/1301adbc-8896-4673-b864-62be01d9be9c)
It still error
![Image](https://github.com/user-attachments/assets/f8d9a85d-4932-4847-b7c4-23663fa4e999)

**Comment by aaronnw** [comment]
We switched recently to using distroless images for aisnode and as a result they no longer have built-in utilities like `tail` or even a shell. Assuming you've got connectivity from your host, you can just install the ais CLI or use the python SDK directly without a debug pod and use your k8s node for your AIS_ENDPOINT. 

We'll need to update the docs regarding `aisnode-debug` so thanks for bringing that up!

**Comment by liuzhiyuan562** [comment]
Thank you very much for your answer!

**Comment by liuzhiyuan562** [comment]
And I met another question when I deploy authn service.(I use the command    ~/kubernetes/kubespray/ais-k8s$ ansible-playbook -i playbooks/hosts.ini playbooks/ais-deployment/ais_deploy_authn.yml -K -e cluster=ais)
I don't know why signature is invalid.
![Image](https://github.com/user-attachments/assets/aa9c29d0-8c88-4c35-9be3-df8dbdb2c61e)

**Comment by gaikwadabhishek** [comment]
Hey @liuzhiyuan562 

I think your singing keys for AIStore and AuthN Server are different. 

check your signing key -
`$ kubectl get secret jwt-signing-key -n ais -o jsonpath="{.data.SIGNING-KEY}" | base64 --decode ; echo
aBitLongSecretKey
`

paste your token over here and verify from your signing key that the signatures match (the content/payload should exactly match) - 
https://jwt.io/

Did you while deploying mention in the CRD that your JWT signing key is in this secret?
To verify - 
`kubectl describe pod ais-proxy-0 -n ais | grep jwt`

You should see some secret mounted as env var

**Comment by gaikwadabhishek** [comment]
I have added a fix for the `aisnode-debug` pod as well

**Comment by liuzhiyuan562** [comment]
Thank you for your answer!
jwt verification is correct.  And the problem is in ais-proxy-0.
![Image](https://github.com/user-attachments/assets/fc7e8617-07d4-485d-8f13-245602383bb9)

and could you tell me how to deploy mention in the CRD that my JWT signing key is in this secret, I can't find the document about deploying authn in k8s.
Here is what I tried to run： I change the authn_secret_name: "" in https://github.com/NVIDIA/ais-k8s/blob/main/playbooks/ais-deployment/roles/ais_deploy_cluster/defaults/main.yml#L9 
![Image](https://github.com/user-attachments/assets/fb88a736-acaa-4f20-ad8b-91bdf314e082)
and i run the command  "ansible-playbook -i playbooks/hosts.ini playbooks/ais-deployment/ais_restart_cluster.yml -K -e cluster=ais"
i met an error
![Image](https://github.com/user-attachments/assets/e43f21c8-896a-41e1-aa54-17596c290106)

**Comment by liuzhiyuan562** [comment]
I remote-attach the cluster, but I can't access the remote bucket.（local is docker,remote is k8s）
![Image](https://github.com/user-attachments/assets/8324e1e8-ac53-43fd-94ab-0c83e94908d1)

**Comment by gaikwadabhishek** [comment]
We do not provide support for debugging local deployments. As a small team, our primary focus is on development and support for **production deployments** at NVIDIA and others.

Regarding your current issue, Docker networking can indeed be complex, and numerous factors can cause issues for you. In our experience, these challenges often stem from network configurations, such as firewalls or communication problems between containers.

While we cannot provide direct debugging support, here are a few suggestions you can try:
1. Run a simple web server like Nginx in your Docker environment and attempt to access it from your Kubernetes setup. This can help isolate any potential network issues.
2. Alternatively, a more straightforward solution might be to add your local machine to your Kubernetes cluster and scale up from there. This approach depends on various factors related to your cluster configuration and goals, but if your aim is to scale, it's likely the simplest option.

Since your initial problem has been resolved, we will be closing this issue. 

Thank you!
