### ISSUE TITLE
DNS name in DirectURL in smap

### ISSUE THREAD

**Issue by and-1** [NVIDIA/aistore#70]
Hi everyone. What about change electable proxy manifest to StatefulSet and use dns name of pod instead ip in directurl in smap? IP is ephemeral resource in k8s.

**Comment by VirrageS** [comment]
Hey!

Thanks for the proposal but we would need more information about the problem it would solve. Could you expand your idea a little bit more? Do you have any problem with current way of deployment?

Here are some our thoughts about this:
* Changing proxy manifest to `StatefulSet` could make sense but is there any particular reason for it? Is it because of nice DNS names like `web-{0..N-1}.nginx.default.svc.cluster.local`?
* There would be a discrepancy between K8s deployment and bare-metal (DNS vs IP). We want to avoid such divergences because it usually leads to more code and more bugs which we want to avoid at any cost.
* As it is true that IP is ephemeral resource we don't relay on it too much. We persist metadata which connects the proxy to its ID. Whenever a proxy IP changes (for example due to Pod restart) we would notice that and just swap the IP address with a new one.

Thanks!
Janusz

**Comment by and-1** [comment]
I experienced with few problem:
1. Simultaneously down/restart all electable proxy. All ip of proxies were changed and target node couldn't connect to it.
2. I tried use proxy ID = pod name (sts). I restart one proxy, after this one is up, i run `ais show cluster smap` and it take long time to get result. In proxy log i see timeout to connect to old ip of proxy. Old ip not present in smap, think some kind of cache.

If change proxy manifest to StatefulSet we will get predictable pod name and direct dns name to pod. Also we can determine primary node in bootstrap phase based on pod index, not use node label. It's more convenient.

**Comment by VirrageS** [comment]
> Simultaneously down/restart all electable proxy. All ip of proxies were changed and target node couldn't connect to it.

This is some limitation that we currently have that targets will not able to correctly function if all the proxies die. For now, we don't have any logic on the target that would try to reconnect or rediscover the new/restarted proxies.

> I tried use proxy ID = pod name (sts). I restart one proxy, after this one is up, i run `ais show cluster smap` and it take long time to get result. In proxy log i see timeout to connect to old ip of proxy. Old ip not present in smap, think some kind of cache.

This sounds like a bug. The node information should be updated on the restart/rejoin of the proxy. We will look into it. Do you use any particular commit/tag?

> Also we can determine primary node in bootstrap phase based on pod index, not use node label.

I think the node label was introduced because we specifically wanted to have a primary on some particular node. So it's kind of a "feature". But I agree, the less we require the easier it is to setup.

**Comment by and-1** [comment]
> This is some limitation that we currently have that targets will not able to correctly function if all the proxies die. For now, we don't have any logic on the target that would try to reconnect or rediscover the new/restarted proxies.

Move to dns in directurl does not resolve this problem?

> This sounds like a bug. The node information should be updated on the restart/rejoin of the proxy. We will look into it. Do you use any particular commit/tag?

3.2.1

**Comment by VirrageS** [comment]
> Move to dns in directurl does not resolve this problem?

It potentially could but it's not obvious if this would work every time. The target tries to connect to the proxy that is next "in line" in terms of primary. But I'm not really sure what would happen if we kill all the proxies and only start some of them. Would targets rejoin correctly? Probably not.

In general the case when all proxies dies is abnormal and for now we don't have a clear solution for the targets. We need to think about it.

> 3.2.1

Oh, this would explain it. We recommend trying 3.3. We have tremendously improved the various cases with target and proxy restart so this issue should be gone when upgraded to this version. Let us know if you stumble upon any issues!

**Comment by and-1** [comment]
> Oh, this would explain it. We recommend trying 3.3. We have tremendously improved the various cases with target and proxy restart so this issue should be gone when upgraded to this version. Let us know if you stumble upon any issues!

I can't reproduce this behavior on 3.3. Thx!

> It potentially could but it's not obvious if this would work every time. The target tries to connect to the proxy that is next "in line" in terms of primary. But I'm not really sure what would happen if we kill all the proxies and only start some of them. Would targets rejoin correctly? Probably not.

Suppose we use statefulset and promote to primary proxy with index 0 (for ex. ais-proxy-0) in boostrap time. When down all proxy and up, target will try connect to next "in line" proxy and failback to ais-proxy-0

**Comment by VirrageS** [comment]
> Suppose we use statefulset and promote to primary proxy with index 0 (for ex. ais-proxy-0) in boostrap time. When down all proxy and up, target will try connect to next "in line" proxy and failback to ais-proxy-0

That would be exactly the idea. We just need to evaluate the whole implementation and work out the bits and pieces - it may take some time though :(. Thanks so much for the ideas and feedback!

**Comment by grmaltby** [comment]
In the direct/discovery etc url dance I am reasonably sure the config I left preferred to probe the proxy clusterIP service first and foremost - if *any* proxy is serving as an endpoint behind that clusterIP service then it would respond with an smap allow target registration to proceed. So if we stop and restart all proxies (power outage scenario) the expectation was that they'd find a cached smap and workout that this is not initial deployment and proxies would cluster and form endpoints behind the clusterIP, at which time targets could begin to retrieve an smap.  The weakness in all that was that the responding endpoint provides an smap that identified the primary by IP, and if that IP is no longer valid (killed the primary again) then the target fails registration. But the fallback there was that the target container would exit and restart, hoping to have better luck with registration timing on the restart.

I'm not convinced that returning a DNS name really helps - if the pod dies then it still won't respond.

**Comment by saiprashanth173** [comment]
Added support for DNS name in DirectURL (in master commit `f2112c1`).
