### ISSUE TITLE
S3 compatibility not working with boto3

### ISSUE THREAD

**Issue by and-1** [NVIDIA/aistore#75]
Hi! I'm trying to use boto3 and i've got problem working with ais as s3 backend. More detail in this issue https://github.com/boto/boto3/issues/2708. Could you resolve this problem in aistore side or any idea how to use it with ais? Boto3 is popular library and used in many projects (like tensorboard).

**Comment by VirrageS** [comment]
Hey!

We are aware of this problem. We generally recommend using `s3cmd` command which handles redirects correctly. But when it comes to using `boto3` library directly unfortunately we don't have any recommendations as we think the `boto3` handles the redirects incorrectly. And from the issue that you've linked, it seems like they have no interest in fixing it.

We will re-evaluate this problem and we will see what we can do about it.

BTW if you are using TensorFlow, the AIStore should work fine as they internally use they own C++ based S3 library. You can find more info here https://github.com/NVIDIA/aistore/blob/master/docs/tensorflow.md. But as you mentioned Tensorboard uses `boto3` so it won't work correctly with AIStore.

Thanks!
Janusz

**Comment by honDhan** [comment]
Hello again!
Boto3 should be compatible with AIStore right now on master. We'll also be releasing v3.4 soon, if you'd like to wait for a release.

There's more info here about how to add compatibility: https://github.com/NVIDIA/aistore/blob/master/docs/s3compat.md#boto3-compatibility

The tl;dr is that you need to build `aisnode` with the build tag `s3rproxy`. Doing this will add compatibility for boto3, but performance will be reduced since your requests will go through proxy nodes.
